DROP TABLE IF EXISTS test_table;

CREATE TABLE test_table (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    adjective TEXT NOT NULL,
    animal TEXT NOT NULL
);
