#!/bin/bash
export HDF5_USE_FILE_LOCKING='FALSE' # Hack to avoid: "OSError: Unable to open file (unable to lock file, errno = 37, error message = 'No locks available')"

#num_files = ls /APF_spectra/all_apf_spectra_highest_SNR -1 | wc -l

# Full run
#python configure_out_dirs.py -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all_apf.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -logfiles 'logfiles'
#python configure_out_dirs.py -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all_apf.csv' -lags_file 'shift_values.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -logfiles 'logfiles'

# Testing run
#python configure_out_dirs.py -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing.csv' -lags_file 'shift_values.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -logfiles 'logfiles'

# Testing
#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_peak_scale_factors -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_1Feb2022.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output1.txt' -start 4 -stop 20 > logfiles/SM_logs/log1.txt 2>&1 & 

#python run_smemp_apf.py  --save_shifted --save_unshifted --save_photon_counts -shifted_out 'NDRS_testing_inj_4' -unshifted_out 'NDRU_testing_inj_4' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_4' -resid_out 'NDRR_testing_inj_4' -results_out 'specmatch_results_testing1_02Mar2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output1.txt' -start 0 -stop 50 > logfiles/SM_logs/log1.txt 2>&1 & 

#python run_smemp_apf.py  --save_shifted --save_unshifted --save_photon_counts -shifted_out 'NDRS_testing_inj_4' -unshifted_out 'NDRU_testing_inj_4' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_4' -resid_out 'NDRR_testing_inj_4' -results_out 'specmatch_results_testing2_02Mar2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output2.txt' -start 50 -stop 100 > logfiles/SM_logs/log2.txt 2>&1 & 

#python run_smemp_apf.py  --save_shifted --save_unshifted --save_photon_counts -shifted_out 'NDRS_testing_inj_4' -unshifted_out 'NDRU_testing_inj_4' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_4' -resid_out 'NDRR_testing_inj_4' -results_out 'specmatch_results_testing3_02Mar2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output3.txt' -start 100 -stop 150 > logfiles/SM_logs/log3.txt 2>&1 & 

#python run_smemp_apf.py  --save_shifted --save_unshifted --save_photon_counts -shifted_out 'NDRS_testing_inj_4' -unshifted_out 'NDRU_testing_inj_4' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_4' -resid_out 'NDRR_testing_inj_4' -results_out 'specmatch_results_testing4_02Mar2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output4.txt' -start 150 -stop 200 > logfiles/SM_logs/log4.txt 2>&1 & 

#python run_smemp_apf.py  --save_shifted --save_unshifted --save_photon_counts -shifted_out 'NDRS_testing_inj_4' -unshifted_out 'NDRU_testing_inj_4' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_4' -resid_out 'NDRR_testing_inj_4' -results_out 'specmatch_results_testing5_02Mar2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output5.txt' -start 200 -stop 250 > logfiles/SM_logs/log5.txt 2>&1 & 

#python run_smemp_apf.py  --save_shifted --save_unshifted --save_photon_counts -shifted_out 'NDRS_testing_inj_4' -unshifted_out 'NDRU_testing_inj_4' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_4' -resid_out 'NDRR_testing_inj_4' -results_out 'specmatch_results_testing6_02Mar2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output6.txt' -start 250 -stop 300 > logfiles/SM_logs/log6.txt 2>&1 & 

#python run_smemp_apf.py  --save_shifted --save_unshifted --save_photon_counts -shifted_out 'NDRS_testing_inj_4' -unshifted_out 'NDRU_testing_inj_4' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_4' -resid_out 'NDRR_testing_inj_4' -results_out 'specmatch_results_testing7_02Mar2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output7.txt' -start 300 -stop 350 > logfiles/SM_logs/log7.txt 2>&1 & 

#python run_smemp_apf.py  --save_shifted --save_unshifted --save_photon_counts -shifted_out 'NDRS_testing_inj_4' -unshifted_out 'NDRU_testing_inj_4' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_4' -resid_out 'NDRR_testing_inj_4' -results_out 'specmatch_results_testing8_02Mar2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output8.txt' -start 350 -stop 400 > logfiles/SM_logs/log8.txt 2>&1 & 

#python run_smemp_apf.py  --save_shifted --save_unshifted --save_photon_counts -shifted_out 'NDRS_testing_inj_4' -unshifted_out 'NDRU_testing_inj_4' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_4' -resid_out 'NDRR_testing_inj_4' -results_out 'specmatch_results_testing9_02Mar2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output9.txt' -start 400 -stop 450 > logfiles/SM_logs/log9.txt 2>&1 & 

#python run_smemp_apf.py  --save_shifted --save_unshifted --save_photon_counts -shifted_out 'NDRS_testing_inj_4' -unshifted_out 'NDRU_testing_inj_4' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_4' -resid_out 'NDRR_testing_inj_4' -results_out 'specmatch_results_testing10_02Mar2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output10.txt' -start 450 -stop 500 > logfiles/SM_logs/log10.txt 2>&1 & 

#python run_smemp_apf.py  --save_shifted --save_unshifted --save_photon_counts -shifted_out 'NDRS_testing_inj_4' -unshifted_out 'NDRU_testing_inj_4' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_4' -resid_out 'NDRR_testing_inj_4' -results_out 'specmatch_results_testing11_02Mar2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output11.txt' -start 500 -stop 550 > logfiles/SM_logs/log11.txt 2>&1 & 

#python run_smemp_apf.py  --save_shifted --save_unshifted --save_photon_counts -shifted_out 'NDRS_testing_inj_4' -unshifted_out 'NDRU_testing_inj_4' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_4' -resid_out 'NDRR_testing_inj_4' -results_out 'specmatch_results_testing12_02Mar2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output12.txt' -start 550 -stop 600 > logfiles/SM_logs/log12.txt 2>&1 & 




#python run_smemp_apf.py  --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output1.txt' -start 0 -stop 20 > logfiles/SM_logs/log1.txt 2>&1 & 

#python run_smemp_apf.py --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output2.txt' -start 20 -stop 40 > logfiles/SM_logs/log2.txt 2>&1 & 

#python run_smemp_apf.py --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output3.txt' -start 40 -stop  60 > logfiles/SM_logs/log3.txt 2>&1 & 

#python run_smemp_apf.py --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output4.txt' -start 60 -stop 80 > logfiles/SM_logs/log4.txt 2>&1 & 

#python run_smemp_apf.py --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output5.txt' -start 80 -stop 100 > logfiles/SM_logs/log5.txt 2>&1 & 

#python run_smemp_apf.py --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output6.txt' -start 100 -stop 120 > logfiles/SM_logs/log6.txt 2>&1 & 

#python run_smemp_apf.py --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output7.txt' -start 120 -stop 140 > logfiles/SM_logs/log7.txt 2>&1 & 

#python run_smemp_apf.py --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output8.txt' -start 140 -stop 160 > logfiles/SM_logs/log8.txt 2>&1 & 

#python run_smemp_apf.py --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output9.txt' -start 160 -stop 180 > logfiles/SM_logs/log9.txt 2>&1 & 

#python run_smemp_apf.py --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output10.txt' -start 180 -stop 200 > logfiles/SM_logs/log10.txt 2>&1 & 

#python run_smemp_apf.py --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output11.txt' -start 200 -stop 220 > logfiles/SM_logs/log11.txt 2>&1 & 

#python run_smemp_apf.py --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output12.txt' -start 220 -stop 240 > logfiles/SM_logs/log12.txt 2>&1 & 

#python run_smemp_apf.py --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output13.txt' -start 240 -stop 260 > logfiles/SM_logs/log13.txt 2>&1 & 

#python run_smemp_apf.py --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output14.txt' -start 260 -stop 280 > logfiles/SM_logs/log14.txt 2>&1 & 

#python run_smemp_apf.py --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output15.txt' -start 280 -stop 300 > logfiles/SM_logs/log15.txt 2>&1 & 




#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_order_edges' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output1.txt' -start 0 -stop 20 > logfiles/SM_logs/log1.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_order_edges' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output2.txt' -start 20 -stop 40 > logfiles/SM_logs/log2.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_order_edges' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output3.txt' -start 40 -stop  60 > logfiles/SM_logs/log3.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_order_edges' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output4.txt' -start 60 -stop 80 > logfiles/SM_logs/log4.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_order_edges' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output5.txt' -start 80 -stop 100 > logfiles/SM_logs/log5.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_order_edges' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output6.txt' -start 100 -stop 120 > logfiles/SM_logs/log6.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_order_edges' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output7.txt' -start 120 -stop 140 > logfiles/SM_logs/log7.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_order_edges' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output8.txt' -start 140 -stop 160 > logfiles/SM_logs/log8.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_order_edges' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output9.txt' -start 160 -stop 180 > logfiles/SM_logs/log9.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_order_edges' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output10.txt' -start 180 -stop 200 > logfiles/SM_logs/log10.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_order_edges' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output11.txt' -start 200 -stop 220 > logfiles/SM_logs/log11.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_order_edges' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output12.txt' -start 220 -stop 240 > logfiles/SM_logs/log12.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_order_edges' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output13.txt' -start 240 -stop 260 > logfiles/SM_logs/log13.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_order_edges' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output14.txt' -start 260 -stop 280 > logfiles/SM_logs/log14.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_order_edges' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output15.txt' -start 280 -stop 300 > logfiles/SM_logs/log15.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output16.txt' -start 0 -stop 20 > logfiles/SM_logs/log16.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output17.txt' -start 20 -stop 40 > logfiles/SM_logs/log17.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output18.txt' -start 40 -stop  60 > logfiles/SM_logs/log18.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output19.txt' -start 60 -stop 80 > logfiles/SM_logs/log19.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output20.txt' -start 80 -stop 100 > logfiles/SM_logs/log20.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output21.txt' -start 100 -stop 120 > logfiles/SM_logs/log21.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output22.txt' -start 120 -stop 140 > logfiles/SM_logs/log22.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output23.txt' -start 140 -stop 160 > logfiles/SM_logs/log23.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output24.txt' -start 160 -stop 180 > logfiles/SM_logs/log24.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output25.txt' -start 180 -stop 200 > logfiles/SM_logs/log25.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output26.txt' -start 200 -stop 220 > logfiles/SM_logs/log26.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output27.txt' -start 220 -stop 240 > logfiles/SM_logs/log27.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output28.txt' -start 240 -stop 260 > logfiles/SM_logs/log28.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output29.txt' -start 260 -stop 280 > logfiles/SM_logs/log29.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_scale_factors --save_baselines --save_photon_counts -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing1_13Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output30.txt' -start 280 -stop 300 > logfiles/SM_logs/log30.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_peak_scale_factors -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_200_stars' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing3_1Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output3.txt' -start 20 -stop 40 > logfiles/SM_logs/log3.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_peak_scale_factors -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_200_stars' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing4_1Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output4.txt' -start 40 -stop 60 > logfiles/SM_logs/log4.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_peak_scale_factors -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_200_stars' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing5_1Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output5.txt' -start 60 -stop 80 > logfiles/SM_logs/log5.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_peak_scale_factors -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_200_stars' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing6_1Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output6.txt' -start 80 -stop 100 > logfiles/SM_logs/log6.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_peak_scale_factors -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_200_stars' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing7_1Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output7.txt' -start 100 -stop 120 > logfiles/SM_logs/log7.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_peak_scale_factors -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_200_stars' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing8_1Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output8.txt' -start 120 -stop 140 > logfiles/SM_logs/log8.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_peak_scale_factors -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_200_stars' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing9_1Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output9.txt' -start 140 -stop 160 > logfiles/SM_logs/log9.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_peak_scale_factors -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_200_stars' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing10_1Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output10.txt' -start 160 -stop 180 > logfiles/SM_logs/log10.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts --save_peak_scale_factors -shifted_out 'NDRS_testing_inj' -unshifted_out 'NDRU_testing_inj' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_200_stars' -resid_out 'NDRR_testing_inj' -results_out 'specmatch_results_testing11_1Feb2022.csv.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output11.txt' -start 180 -stop 200 > logfiles/SM_logs/log11.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts -shifted_out 'NDRS_testing_inj_2' -unshifted_out 'NDRU_testing_inj_2' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_2' -resid_out 'NDRR_testing_inj_2' -results_out 'specmatch_results_testing2_18Jan2021.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output2.txt' -start 0 -stop 4 > logfiles/SM_logs/log2.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted --save_shifts -shifted_out 'NDRS_testing_inj_3' -unshifted_out 'NDRU_testing_inj_3' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/injected_spectra_3' -resid_out 'NDRR_testing_inj_3' -results_out 'specmatch_results_testing3_18Jan2021.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output3.txt' -start 0 -stop 4 > logfiles/SM_logs/log3.txt 2>&1 & 

#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing2_10Dec2021.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -log 'logfiles/SM_outputs/specmatch_output2.txt' -start 5 -stop 10 > logfiles/SM_logs/log2.txt 2>&1 & 

#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing3_10Dec2021.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -log 'logfiles/SM_outputs/specmatch_output3.txt' -start 10 -stop 15 > logfiles/SM_logs/log3.txt 2>&1 & 

#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing4_10Dec2021.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -log 'logfiles/SM_outputs/specmatch_output4.txt' -start 15 -stop 20 > logfiles/SM_logs/log4.txt 2>&1 & 

#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing5_10Dec2021.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -log 'logfiles/SM_outputs/specmatch_output5.txt' -start 20 -stop 25 > logfiles/SM_logs/log5.txt 2>&1 & 

#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing6_10Dec2021.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -log 'logfiles/SM_outputs/specmatch_output6.txt' -start 25 -stop 30 > logfiles/SM_logs/log6.txt 2>&1 & 

#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing7_10Dec2021.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -log 'logfiles/SM_outputs/specmatch_output7.txt' -start 30 -stop 35 > logfiles/SM_logs/log7.txt 2>&1 & 

#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing8_10Dec2021.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -log 'logfiles/SM_outputs/specmatch_output8.txt' -start 35 -stop 40 > logfiles/SM_logs/log8.txt 2>&1 & 

#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing9_10Dec2021.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -log 'logfiles/SM_outputs/specmatch_output9.txt' -start 40 -stop 45 > logfiles/SM_logs/log9.txt 2>&1 & 

#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing10_10Dec2021.csv' -results_type 'testing' -plots_out 'SM_output_plots_testing' -log 'logfiles/SM_outputs/specmatch_output10.txt' -start 45 -stop 50 > logfiles/SM_logs/log10.txt 2>&1 & 

#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/additional_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_tests11.csv' -plots_out 'SM_output_plots_testing' -log 'specmatch_output11.txt' -start 25 -stop 50 > logfiles/log11.txt 2>&1 & 
#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/additional_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_tests12.csv' -plots_out 'SM_output_plots_testing' -log 'specmatch_output12.txt' -start 50 -stop 75 > logfiles/log12.txt 2>&1 & 
#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/additional_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_tests13.csv' -plots_out 'SM_output_plots_testing' -log 'specmatch_output13.txt' -start 75 -stop 100 > logfiles/log13.txt 2>&1 & 
#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/additional_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_tests14.csv' -plots_out 'SM_output_plots_testing' -log 'specmatch_output14.txt' -start 100 -stop 114 > logfiles/log14.txt 2>&1 & 


# Full run
#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all1_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output1.txt' -start 0 -stop 50 > logfiles/SM_logs/log1.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all2_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output2.txt' -start 50 -stop 100 > logfiles/SM_logs/log2.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all3_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output3.txt' -start 100 -stop 150 > logfiles/SM_logs/log3.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all4_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output4.txt' -start 150 -stop 200 > logfiles/SM_logs/log4.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all5_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output5.txt' -start 200 -stop 250 > logfiles/SM_logs/log5.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all6_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output6.txt' -start 250 -stop 300 > logfiles/SM_logs/log6.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all7_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output7.txt' -start 300 -stop 350 > logfiles/SM_logs/log7.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all8_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output8.txt' -start 350 -stop 400 > logfiles/SM_logs/log8.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all9_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output9.txt' -start 400 -stop 450 > logfiles/SM_logs/log9.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all10_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output10.txt' -start 450 -stop 500 > logfiles/SM_logs/log10.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all11_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output11.txt' -start 500 -stop 550 > logfiles/SM_logs/log11.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all12_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output12.txt' -start 550 -stop 600 > logfiles/SM_logs/log12.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all13_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output13.txt' -start 600 -stop 650 > logfiles/SM_logs/log13.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all14_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output14.txt' -start 650 -stop 700 > logfiles/SM_logs/log14.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all15_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output15.txt' -start 700 -stop 750 > logfiles/SM_logs/log15.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all16_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output16.txt' -start 750 -stop 800 > logfiles/SM_logs/log16.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all17_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output17.txt' -start 800 -stop 850 > logfiles/SM_logs/log17.txt 2>&1 & 

#python run_smemp_apf.py --save_shifted --save_unshifted -shifted_out 'NDRS_all_apf' -unshifted_out 'NDRU_all_apf' -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_all_apf' -results_out 'specmatch_results_all18_11Jan2022.csv' -results_type 'all_apf' -plots_out 'SM_output_plots_all_apf' -lags_file 'shift_values.csv' -log 'logfiles/SM_outputs/specmatch_output18.txt' -start 850 -stop 902 > logfiles/SM_logs/log18.txt 2>&1 & 


#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing10.csv' -plots_out 'SM_output_plots_testing' -log 'specmatch_output10.txt' -start 450 -stop 500  & 
#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing11.csv' -plots_out 'SM_output_plots_testing' -log 'specmatch_output11.txt' -start  500 -stop  550  & 
#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing12.csv' -plots_out 'SM_output_plots_testing' -log 'specmatch_output12.txt' -start  550 -stop  600  & 
#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing13.csv' -plots_out 'SM_output_plots_testing' -log 'specmatch_output13.txt' -start  600 -stop  650  & 
#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing14.csv' -plots_out 'SM_output_plots_testing' -log 'specmatch_output14.txt' -start  650 -stop  700  & 
#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing15.csv' -plots_out 'SM_output_plots_testing' -log 'specmatch_output15.txt' -start  700 -stop  750  & 
#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing16.csv' -plots_out 'SM_output_plots_testing' -log 'specmatch_output16.txt' -start  750 -stop  800  & 
#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/all_apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing17.csv' -plots_out 'SM_output_plots_testing' -log 'specmatch_output17.txt' -start  800 -stop  810  
#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing.csv' -plots_out 'SM_output_plots_testing' -start = 850 -stop = 900  & 
#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing.csv' -plots_out 'SM_output_plots_testing' -start = 900 -stop = 950  & 
#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing.csv' -plots_out 'SM_output_plots_testing' -start = 950 -stop = 1000  & 
#python run_smemp_apf.py -in '/mnt_home/azuckerman/BL_APF_DAP/APF_spectra/apf_spectra_highest_SNR' -resid_out 'NDRR_testing' -results_out 'specmatch_results_testing.csv' -plots_out 'SM_output_plots_testing' -start = 1000 -stop = 1050  & 

